// Rebuild with Node.js + pptxgenjs. These are optional authoring dependencies;
// no Node packages are needed to RUN the supplied experiments.
const pptxgen = require('pptxgenjs');
const fs = require('fs'); const path=require('path');
const ROOT=path.resolve(__dirname,'..');
const D=id=>JSON.parse(fs.readFileSync(path.join(ROOT,'results/saved',id,'result.json')));
const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='SCALE-LI research walkthrough';
pptx.subject='History, reproducible mechanisms and baseline preparation';pptx.title='Learned indexes: from positions to compressed layouts';pptx.company='Research meeting';pptx.lang='en-US';
pptx.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-US'};
const C={ink:'162733',muted:'526571',accent:'11727B',light:'EFF5F6',line:'D9E3E6',white:'FFFFFF',dark:'112C39',amber:'945E22'};
let index=[]; const cleanNotes=JSON.parse(fs.readFileSync(path.join(__dirname,'notes_text.json')));
function txt(s,t,x,y,w,h,sz=18,opt={}){s.addText(t,{x,y,w,h,fontFace:'Aptos',fontSize:sz,color:C.ink,margin:0,breakLine:false,paraSpaceAfterPt:7,fit:'shrink',...opt});}
function base(title,sub,tag,lesson,source,notes){let s=pptx.addSlide();s.background={color:C.white};let n=pptx._slides.length;
 txt(s,tag.toUpperCase(),.6,.27,11.4,.22,10,{color:C.accent,bold:true,charSpacing:1.1});txt(s,title,.6,.70,12.1,.66,30,{bold:true,fontFace:'Aptos Display'});if(sub)txt(s,sub,.6,1.4,12.1,.46,16,{color:C.muted});
 s.addShape(pptx.ShapeType.line,{x:.6,y:6.96,w:12.1,h:0,line:{color:C.line,width:1}});
 if(lesson)txt(s,`L${lesson}   python3 walkthrough.py demo ${lesson}`,.6,6.49,11.4,.32,14,{fontFace:'Aptos Mono',color:C.accent});
 txt(s,source,.6,7.07,11.6,.21,9,{color:C.muted});txt(s,String(n).padStart(2,'0'),12.12,7.05,.6,.25,11,{align:'right',color:C.muted});
 notes=cleanNotes[n-1]||notes;s.addNotes(notes||'');index.push({slide:n,title,lesson:lesson||null,source,notes});return s;}
function card(s,label,body,x,y,w=4.6,h=1.15){s.addShape(pptx.ShapeType.rect,{x,y,w,h,fill:{color:C.light},line:{color:C.light}});txt(s,label,x+.17,y+.12,w-.34,.27,14,{bold:true,color:C.accent});txt(s,body,x+.17,y+.47,w-.34,h-.54,17);}
function chart(s,name,x=5.5,y=1.95,w=7.15,h=4.27){let p=path.join(__dirname,'figures',name+'.png');let b=fs.readFileSync(p),iw=b.readUInt32BE(16),ih=b.readUInt32BE(20),k=Math.min(w/iw,h/ih);s.addImage({path:p,x:x+(w-iw*k)/2,y:y+(h-ih*k)/2,w:iw*k,h:ih*k});}
function table(s,heads,rows,widths,x=.6,y=2.04,rowH=.65,sz=16){let xx=x;heads.forEach((t,i)=>{s.addShape(pptx.ShapeType.rect,{x:xx,y,w:widths[i],h:rowH,fill:{color:C.dark},line:{color:C.white,width:1}});txt(s,t,xx+.12,y+.12,widths[i]-.24,rowH-.15,sz,{color:C.white,bold:true});xx+=widths[i]});rows.forEach((row,j)=>{let xx=x;row.forEach((t,i)=>{s.addShape(pptx.ShapeType.rect,{x:xx,y:y+(j+1)*rowH,w:widths[i],h:rowH,fill:{color:j%2?C.white:C.light},line:{color:C.line,width:.5}});txt(s,String(t),xx+.12,y+(j+1)*rowH+.11,widths[i]-.24,rowH-.17,sz);xx+=widths[i]})})}
function simple(title,sub,tag,items,source,notes){let s=base(title,sub,tag,null,source,notes);items.forEach((x,i)=>card(s,x[0],x[1],.6+i*4.13,2.25,3.86,2.75));return s;}
// 1
let s=base('Learned indexes: from positions to compressed layouts','A historical walkthrough with inspectable evidence and runnable experiments','First supervisor meeting',null,'SCALE-LI research workspace • 8 September 2026','Opening: I want to establish what exists, what its evidence supports, and which baseline to reproduce next. The custom compression prototype is a research control, not the state of the art. Spend 30 seconds here.');
card(s,'UNDERSTAND','What changed at each stage of the literature?',.6,2.5,3.86,2.1);card(s,'RUN','Small offline experiments linked by lesson ID.',4.74,2.5,3.86,2.1);card(s,'DECIDE','Agree on the next common-data reproduction milestone.',8.88,2.5,3.86,2.1);txt(s,'Existing work first. A new contribution comes after the baseline.',.65,5.25,11.8,.5,24,{bold:true});
//2
s=base('Three evidence labels — three different claims','A rerun of arithmetic is not a reproduction of a published system.','How to read this deck',null,'Coverage: docs/APPROACHES.md • Raw evidence: results/saved/','The deck distinguishes published observations, teaching mechanisms and native measurements. All new local demos use a synthetic fixture. There is no common apples-to-apples SOTA ranking yet. RadixSpline is source-transcribed, not commit-pinned. ALEX/PGM adapters remain uncompiled against upstream.');
table(s,['Label','What it supports','Example'],[['PUBLISHED','What the paper reports in its setup','NFL Tables 1–2; CSV promoted keys'],['TEACHING DEMO','Inspect a mechanism and its objective','Two-stage fitting; virtual points'],['LOCAL MEASUREMENT','What tested code does on this fixture','RadixSpline-derived; custom map']],[2.65,4.45,5.0],.6,2.1,.82,17);txt(s,'No full ALEX / PGM / NFL / CSV upstream reproduction is claimed.',.65,5.85,11.8,.45,19,{bold:true,color:C.amber});
//3
s=base('The history is branching, not a single leaderboard','The papers improve different parts of the same access path.','2018 → 2026',null,'Primary-source registry: sources/registry.json','Walk left to right verbally. Modeling, dynamic placement, distribution transformation and compression develop in parallel. Publication order does not imply that each new method wins under every contract.');
table(s,['Period','Main idea','Representative approaches'],[['2018–20','Predict positions; bound error; build cheaply','RMI → FITing-Tree → PGM / RadixSpline'],['2020–23','Maintain learned structure under updates','ALEX → LIPP → SALI'],['2021–24','Compress while retaining direct access','LA-vector → LeCo'],['2022–25','Change the distribution / positions','NFL → CSV'],['2025–26','Evaluate robustness and maintenance tails','SEA comparison / RoBin / LINE']],[1.65,4.8,5.65],.6,2.02,.69,16);
//4
s=base('Start with the task: exact ordered lookup','Use case: look up integer-keyed records and scan their successors.','L01 • synthetic dataset','01','Fixture: evidence/dense_sparse_fixture_uint64 • SHA-256 in its manifest','Show that the same numerical keys can have alternating density. This is a deliberately small, bundled 16,384-key synthetic fixture, not OSM/Facebook and not a real trace. Read-only experiments load all keys; dynamic controls later load 75%. The graph is the first 1,024 fixture records, not the whole global distribution.');
card(s,'INPUT','16,384 distinct sorted uint64 keys. Alternating dense and sparse intervals.',.6,2.05);card(s,'OUTPUT','lower_bound(k): the first stored key that is at least k.',.6,3.36);card(s,'BASELINE','Binary search gives an exact answer without a fitted predictor.',.6,4.67);chart(s,'dataset');
//5
let r=D('01');s=base('2018 · predict rank, then specialize','RMI introduces model-guided navigation and exact correction.','PUBLISHED IDEA + INDEPENDENT TEACHING MODEL','01','Kraska et al., SIGMOD 2018 • L01 is NOT the authors’ RMI implementation','Explain model direction key→rank, then model dispatch. The chart is our small two-stage teaching model, fitted with ordinary least squares. Its capacity sweep holds keys fixed and counts leaf models; the root is additional. It measures fitting error, not runtime. The correction test checks stored and missing queries against Python bisect. Ask whether lower error justifies more models. Source: https://arxiv.org/abs/1712.01208');
card(s,'MECHANISM','A root prediction selects a local model. That model predicts a position.',.6,2.05);card(s,'WHAT WE CHECK',r.exact_query_checks.toLocaleString()+' exact query checks after corrective search.',.6,3.36);card(s,'TRADE-OFF','More models can help fitting, but consume space and add routing work.',.6,4.67);chart(s,'model_sweep');
//6
s=base('2019 · make prediction error an explicit parameter','FITing-Tree: piecewise-linear approximation with a chosen error bound.','LITERATURE • NOT LOCALLY REPRODUCED',null,'Galakatos et al., SIGMOD 2019 • https://arxiv.org/abs/1801.10207','Explain a bound as a design control rather than minimizing average squared error. The paper uses a cost model to balance space and lookup latency. This slide is literature, not a claim that our teaching model implements FITing-Tree. A native bounded-search illustration follows in L02 using RadixSpline.');
card(s,'BEFORE','A good average fit can still leave difficult local regions.',.6,2.2,3.86,2.6);card(s,'CHANGE','Partition into linear segments that meet a specified error tolerance.',4.74,2.2,3.86,2.6);card(s,'COST','Tighter tolerance may require more segments and metadata.',8.88,2.2,3.86,2.6);txt(s,'Prediction + bounded correction, not “the model must be exact.”',.65,5.45,11.8,.6,24,{bold:true});
//7
s=base('2020 · build a hierarchy of bounded models','PGM indexes the segments recursively and supplies static and dynamic variants.','LITERATURE • UPSTREAM ADAPTER NOT VALIDATED',null,'Ferragina & Vinciguerra, PVLDB 2020, §§2–4 • doi:10.14778/3389133.3389135','PGM constructs piecewise-linear models and recursively indexes segment keys. The paper also provides dynamic and compressed-model variants. Do not confuse model compression with compression of source keys. An optional adapter exists in the old prototype but has not been compiled against upstream here. Source: https://www.vldb.org/pvldb/vol13/p1162-ferragina.pdf');
card(s,'MODELS OF MODELS','Each level narrows the next search; the final interval is corrected exactly.',.6,2.2,3.86,2.6);card(s,'BOUND + SPACE','Error tolerance determines the fit/space/search trade-off.',4.74,2.2,3.86,2.6);card(s,'DISTINCTION','Compressing model parameters is not automatically compressing the keys.',8.88,2.2,3.86,2.6);
//8
r=D('02');s=base('2020 · RadixSpline makes the path concrete','One-pass spline construction + radix directory + exact bounded search.','SOURCE-DERIVED NATIVE EXPERIMENT','02','Kipf et al., aiDM 2020 • third_party/radix_spline/PROVENANCE.md • results/saved/02/','LIVE DEMO: python3 walkthrough.py demo 02. The native code is a transcription of three MIT source headers fetched via the web view, not a commit-pinned checkout; provenance is explicit. It is not an independent simplified spline invented under the paper name. Same 16,384 keys, 100,000 queries, epsilon 32, radix bits 10. Maximum bound 66 keys includes the implementation’s exclusive-end convention. Five warmed same-process repeats, not independent performance trials. Record payloads and updates are absent.');
card(s,'FINAL WINDOW','At most '+r.max_search_window_keys+' keys in this run, with ε = 32.',.6,2.05);card(s,'EXACTNESS','Every query in the measured trace checked against std::lower_bound.',.6,3.36);card(s,'SPACE SCOPE',r.key_bytes.toLocaleString()+' key bytes + '+r.auxiliary_index_bytes.toLocaleString()+' auxiliary bytes; no payloads.',.6,4.67);chart(s,'radix');
//9
s=base('2020–21 · updates require a storage strategy','ALEX and LIPP address insertion and conflicts differently.','LITERATURE • NOT LOCALLY REPRODUCED',null,'Ding et al., ALEX, SIGMOD 2020 • Wu et al., LIPP, PVLDB 2021','ALEX uses gapped data nodes and model-guided search with cost-driven adaptations. LIPP focuses on predicted placement and recurses into conflict nodes. Do not call a sorted overlay/rebuild a reproduction of either system. Main follow-on question: how does density, insertion order and growth change costs? Sources: https://github.com/microsoft/ALEX ; https://www.vldb.org/pvldb/vol14/p1276-wu.pdf');
card(s,'ALEX','Use gaps and adaptive expansion/splitting to accommodate writes.',.6,2.2,5.84,2.2);card(s,'LIPP','Use predicted placement; represent collisions through additional nodes.',6.86,2.2,5.84,2.2);txt(s,'The baseline must include inserts, scans, memory and maintenance — not reads alone.',.65,5.15,11.8,.83,23,{bold:true});
//10
r=D('03');s=base('2022 · NFL changes the input distribution','Transform numerical keys before building an After-Flow Learned Index.','PUBLISHED RESULT • TABLE ARITHMETIC','03','Uploaded NFL paper • Table 1 p.3; framework pp.4–6 • results/saved/03/','The bar chart is Table 1: ALEX with and without a numerical normalizing-flow transformation on Facebook. 4.13 to 9.16 Mops/s and maximum height 11 to 3. This table is not the overall NFL-versus-all-baselines experiment. Its operation mix and batch size are not specified by that table; do not borrow later settings. The command checks/recomputes paper arithmetic; it does not train or execute NFL.');
card(s,'KEY CHANGE','Original key → numerical flow → transformed key → learned index.',.6,2.05);card(s,'REPORTED EXAMPLE','Facebook: max tree height 11 → 3. Throughput 4.13 → 9.16 Mops/s.',.6,3.36);card(s,'NEXT QUESTION','Does the lower search cost repay the online transformation?',.6,4.67);chart(s,'nfl');
//11
s=base('The cost of a transformation is part of the result','Batching changes the per-key economics; latency definitions also matter.','PUBLISHED RESULT • NOT A LOCAL MEASUREMENT','03','NFL Table 2 p.6; §4.3 p.10; §4.2 discussion p.10','Transform-only 2H2L average is 169.53 ns/key at batch 1 and 8.38 at batch 256. These are neither whole-query averages nor individual-request tail values. The paper defines reported P99 as batch P99 divided by batch size, and reports cases where transform overhead hurts. The literal table plot comes from the user-provided source.');
card(s,'SINGLE KEY','169.53 ns/key average transformation cost, reported for 2H2L.',.6,2.05);card(s,'BATCH OF 256','8.38 ns/key average, in that same table.',.6,3.36);card(s,'DO NOT CONFLATE','Batch-normalized P99 is not the P99 of individual request latency.',.6,4.67);chart(s,'batching');
//12
s=base('2021–24 · compress without losing efficient access','A parallel line of work: LA-vector and LeCo.','LITERATURE • NOT LOCALLY REPRODUCED',null,'Boffa et al., ALENEX 2021 • Liu et al., LeCo, SIGMOD 2024, §5.2','LA-vector combines learned compression and exact rank/select. LeCo learns serial relationships and stores exact residuals with random access. LeCo reports up to16% Seek throughput improvement vs the second-best tested configuration in its RocksDB experiment:900M generated records,20-byte keys,400-byte values,64threads. This is a different contract, not a predicted gain for our in-memory map. Source https://arxiv.org/html/2306.15374#S5.SS2');
card(s,'LA-VECTOR','A learned compressed representation with exact rank/select operations.',.6,2.2,3.86,2.55);card(s,'LECO','Model position → value, then store exact residuals and partition metadata.',4.74,2.2,3.86,2.55);card(s,'PUBLISHED SYSTEM RESULT','LeCo reports up to 16% higher Seek throughput in its RocksDB setup.',8.88,2.2,3.86,2.55);txt(s,'That experiment uses 900M generated records and 64 threads — not our workload.',.65,5.35,11.8,.75,20,{color:C.muted});
//13
r=D('04');s=base('Run a control: compression can save space yet slow reads','Hold keys, block boundaries, query traces and exact map semantics fixed.','LOCAL EXPERIMENTAL MAP • NOT LECO','04','results/saved/04/ • 16,384 synthetic records; 10K ops/seed; three seeds; full initial load','These new measurements use the shipped binary fixture, not the earlier generated dense_sparse archive. Raw/rank and packed variants have identical workload traces within each seed, verified values and full scans. Space includes8-byte values and metadata. Do not compare directly to lesson02 keys-only footprint. The result is an ablation of our custom map, not SOTA replication. The scatter makes clear that minimizing bytes is not necessarily maximizing throughput.');
card(s,'REPRESENTATIONS','Raw, FOR, restarted delta and integer-linear residual blocks.',.6,2.05);card(s,'MATCHED COMPARISONS','Raw/rank → packed/rank → packed/byte. Packed/binary is another control.',.6,3.36);card(s,'OBSERVATION','The packed footprint is smaller. This run does not show a throughput win.',.6,4.67);chart(s,'compression');
//14
s=base('CSV · change positions with virtual points','Refit models and reconstruct selected subtrees when the cost condition permits.','PUBLISHED RESULT • ATTACHED 2024/25 VERSION',null,'Uploaded CSV paper • Figure 2 p.2; §6.1 p.9; Figure 7 p.10; Table 4 p.11','The attachment has inconsistent publication labels; refer to the provided version rather than resolving dates silently. Its 34% result refers to promoted keys, queried100times each and averaged. The preprocessing numbers on the next table usealpha0.1, while34%is a maximum acrosssettings; they are not one matched result. Algorithm1 smooths a singlemodel; Algorithm2 applies it to selected subtrees. No official hierarchical CSV implementation is included.');
card(s,'MECHANISM','Insert virtual positions, refit, then potentially reduce traversal depth.',.6,2.08,3.86,2.35);card(s,'REPORTED BENEFIT','Up to 34% less query time for the selected promoted keys.',4.74,2.08,3.86,2.35);card(s,'COST TO REPORT','At α = 0.1, ALEX preprocessing ranges from 889 to 2,902 seconds.',8.88,2.08,3.86,2.35);txt(s,'Conditional query gain ≠ whole-workload speedup. Preprocessing is not free.',.65,5.2,11.8,.8,23,{bold:true});
//15
r=D('05');s=base('Make virtual-point smoothing inspectable','A ten-key teaching example exposes exactly what the objective changes.','INDEPENDENT TEACHING DEMO • NOT CSV','05','experiments/lessons.py::lesson05 • inherited virtual_points_lab.py • results/saved/05/','LIVE DEMO python3 walkthrough.py demo05. State before running that these are our keys andbudget3, not thepaper’sfigure10keysbudget5. Theobjective is OLS SSE over the augmented set; originalkeySSE is also retained. Greedy examines candidates eachstep; exhaustive evaluates1351subsets. Do not call this optimizedCSVAlgorithm1 or claim its complexity bound. The lesson proves only that changingpositionscan improve this fit.');
card(s,'INPUT','10 explicit keys; budget = 3 virtual points. No hidden dataset.',.6,2.05);card(s,'VERIFY','Exhaustive search provides a ceiling over this finite candidate set.',.6,3.36);card(s,'LIMIT','These are fitting errors, not query-time savings. The full CSV hierarchy is absent.',.6,4.67);chart(s,'virtual');
//16
r=D('06');s=base('The project hypothesis must distinguish rank from bytes','Lossless compression changes representation, not the order of the same keys.','LOCAL EXPERIMENTAL GEOMETRY','06','results/saved/06/layout_*.csv • same fixture and block boundaries; full initial load','Run06orusethe savedpage. Check ranknormalizedMSEsameall3layouts. Byte normalizedMSE decreases raw→min→smooth, but initialblockerror increasesonthisfixture. Exact values are in JSON/CSV. Do not reuse the previous archive numbers: the fixturehereisdifferent. The plot only shows block displacement; do not putMSEandlatencyonthesameaxis.');
card(s,'INVARIANT','Logical rank model unchanged across raw, packed and density-target layouts.',.6,2.05);card(s,'WHAT WE MEASURE','Encoded bytes, normalized fitting error, initial block displacement.',.6,3.36);card(s,'OBSERVATION','Lower byte-fitting error did not imply lower block-search error here.',.6,4.67);chart(s,'geometry');
//17
s=base('Updates expose another cost: rebuilding a region','A compression benefit must survive maintenance, not just the initial build.','MATCHED LOCAL UPDATE CONTROLS','06','results/saved/06/updates_*.json • same trace; 75% initial load; read-heavy mix','Both raw and packedcontrolsusesameseedtrace,10kops,75%load,byte router. Herebothrecord25compactions; rawhasinsertP99~173.552uspacked273.533us. ThesearefreshLinuxtracefigures,notuserMacvalues. P99correlatesmaintenancebutprofilingneededtoattribute time. Operation timing includes synchronousrebuild. Remainingdebt isdrained andreported separately.');
card(s,'UPDATE PATH','Recent changes enter a sorted overlay. A full overlay triggers local rebuilding.',.6,2.05);card(s,'FAIR CONTROL','Raw and compressed variants both perform maintenance on the same trace.',.6,3.36);card(s,'QUESTION','Which cost comes from decoding, copying, allocation, fitting or rewriting?',.6,4.67);chart(s,'updates');
//18
s=base('2025–26 · robustness is part of the baseline','Recent work reinforces the need to vary workloads and control maintenance tails.','LITERATURE • NOT LOCALLY REPRODUCED',null,'SEA 2025 comparison • RoBin, PACMMOD 2025 / SIGMOD context • LINE, SIGMOD 2026','SEA includesoptimizedtraditionalandcompressedcontrols,soourstdmapnotenough. RoBinpublicationlabelSep2025thoughfileSIGMOD26: evaluatesinitialsampling,size,insertionorder and performanceovercases. LINEJune2026targets localhardness,globalskew and longstructuralchanges withgroup-enhancedleaves/cacheoptimizedtree/groupmigrations. Do not claimindependentreplicationorstateLINEuniversallywins. URLs in source registry.');
card(s,'STRONG CONTROLS','Compare against optimized traditional and compressed representations.',.6,2.2,3.86,2.5);card(s,'ROBUSTNESS GRID','Vary initial sampling, initial size, insertion order and domain growth.',4.74,2.2,3.86,2.5);card(s,'MAINTENANCE','LINE decomposes lengthy structural changes into group-wise migrations.',8.88,2.2,3.86,2.5);txt(s,'Do not infer a universal ranking from a favorable read-only dataset.',.65,5.35,11.8,.7,23,{bold:true});
//19
s=base('What is ready — and what still needs reproduction','A transparent baseline plan is stronger than overstating coverage.','IMPLEMENTATION STATUS',null,'docs/APPROACHES.md • evidence/VALIDATION.md','Pointatthisexplicitcoverage: literaturedeckcompleteforthe selectedapproaches,runnablemechanisms/nativeprototypepass. Stillno fullupstreamSOTA matrix, norealdatameasurements. NativeRadixsource-derivednotpinned. ThegoalnextisnotmorecomplexAIbutcrediblecomparison.');
table(s,['Ready now','Not yet established'],[['Chronological deck + traceable paper evidence','Full benchmark reproduction for each paper'],['7 executable lessons + saved offline outputs','Authors’ RMI/FITing/ALEX/PGM/NFL/CSV runs'],['Native source-derived RadixSpline comparison','A commit-pinned upstream parity claim'],['Exact custom-map compression/update controls','Improvement over SOTA or real-data robustness']],[6.1,6.0],.6,2.0,.77,17);
//20
s=base('Agree on the next baseline milestone','Use the history to choose experiments, not to preselect a new method.','SUPERVISOR DISCUSSION',null,'Proposed next work • not completed experiments','Closewiththreeconcretedecisions: which APIs/staticfirstorupdates; whichofficial implementations and real datasets; what constitutesaresult(e.g.memorybudget,tails,pairedtraces). Suggest ALEX,PGM,RS and optimizedconventionalbaselinebutleavethesupervisorchoice. Compressionresearchcanthenbeginfromthatfoundation.');
card(s,'1 · COMMON CONTRACT','Static lower_bound first? Or point lookup, scans and updates with fixed payloads?',.6,2.2,3.86,2.55);card(s,'2 · REPRODUCTIONS','Agree on pinned upstream implementations and the first real corpus.',4.74,2.2,3.86,2.55);card(s,'3 · SUCCESS METRICS','Memory budget, exactness, lookup/scan cost, write tails and rebuild debt.',8.88,2.2,3.86,2.55);txt(s,'Next milestone: one reproducible common-data comparison, then iterate.',.65,5.42,11.8,.6,23,{bold:true});
//21
s=base('Appendix · one command for each evidence trail','Every lesson ends in a result JSON and an offline report section.','RUN MAP',null,'Entrypoint: walkthrough.py • Optional notebook: Walkthrough.ipynb','Foranunplannedquestionlookupthe ID; donotstartauthorrepositorydownloads. Paperlesson03isfastarithmetic notfullNF. This tableisapracticalnavigationindex.');
table(s,['ID','Run / inspect','Classification'],[['01','Rank fitting + corrected search','Teaching model'],['02','RadixSpline / binary exact lower_bound','Source-derived native'],['03','NFL table ratios + batching','Published evidence'],['04','Matched compression and routing','Experimental native map'],['05','Greedy / exhaustive virtual points','Teaching model'],['06','Geometry + matched mutation tails','Experimental native map'],['07','Archive / Mac evidence checks','Audit; no fresh timing']],[.8,6.5,4.8],.6,1.99,.53,15);
//22
s=base('Appendix · rehearse once; keep a fallback open','Do not debug installations or download datasets during the meeting.','REHEARSAL',null,'docs/REHEARSAL.md • All timings are machine-dependent','PreparationneedsCMakecompilerPython3.10. Useralreadycompiledoldprojectbutthisisanewfolder build separately,donotoverwriteoldfolder. Showexpected3CTestentries12Pythonmethodsandsevensteps. PDFplotsaresavedbaseline whilelocalreportshowsownMacresults.');
card(s,'BEFORE THE MEETING','python3 walkthrough.py prepare\npython3 walkthrough.py demo all',.6,2.05,6.0,1.45);card(s,'LIVE: ONLY THREE COMMANDS','demo 02\ndemo 05\ndemo 06',.6,3.75,6.0,1.8);card(s,'IF A RUN FAILS','Open results/saved/report.html. Explain that these are recorded runs with their environment.',7.0,2.05,5.7,1.65);card(s,'WHICH TAB?','Use this deck and the numbered result page. The older code guide is only a reference.',7.0,4.0,5.7,1.55);
//23
s=base('Appendix · source map, foundations','The user-provided NFL and CSV versions are preserved in sources/.','PRIMARY SOURCES',null,'Full references and URLs: sources/registry.json','Referencesareoutsideconnectedsourcecommands.Primarypublishedapproachesmethodsnotgeneralreviews.');
table(s,['Source','Read for'],[['Kraska et al. • SIGMOD 2018 • arXiv:1712.01208','RMI / learned key-to-position viewpoint'],['Galakatos et al. • SIGMOD 2019 • arXiv:1801.10207','FITing-Tree / bounded approximation'],['Ferragina & Vinciguerra • PVLDB 2020','PGM / recursive models and variants'],['Kipf et al. • aiDM 2020 • arXiv:2004.14541','RadixSpline / single-pass construction'],['Ding et al. • SIGMOD 2020 • microsoft/ALEX','ALEX / adaptive dynamic structure'],['Wu et al. • PVLDB 2021 • p1276-wu.pdf','LIPP / precise placement']],[7.2,4.9],.6,2.0,.60,15);
//24
s=base('Appendix · source map, transformation and compression','Keep each result attached to its own experimental contract.','PRIMARY SOURCES',null,'Full references and URLs: sources/registry.json','TheCSVdateisnotresolvedsilently; the papercontentisreproducedasprovided. RoBinlabel2025PACMMOD,LINE2026. Theformerreadingscontained2026filename-onlylabels;useactualpaperpublicationinformationhere.');
table(s,['Source','Read for'],[['NFL • uploaded 2205.11807v1.pdf','Tables 1–2; batching and latency definitions'],['CSV • uploaded 2408.06134v3.pdf','Algorithms 1–2; promoted-key measurements'],['Boffa et al. • ALENEX 2021','LA-vector / learned compressed rank/select'],['LeCo • SIGMOD 2024 • arXiv:2306.15374','Serial correlations / random access'],['SEA 2025 • doi:10.4230/LIPIcs.SEA.2025.5','Strong static comparisons'],['RoBin • doi:10.1145/3749188; LINE • 3802080','Robustness / maintenance frontier']],[7.2,4.9],.6,2.0,.60,15);
fs.writeFileSync(path.join(__dirname,'slide_index.json'),JSON.stringify(index,null,2));
fs.writeFileSync(path.join(__dirname,'SPEAKER_NOTES.md'),index.map(x=>`## ${String(x.slide).padStart(2,'0')} — ${x.title}\n\n${x.notes}\n\n${x.lesson?'Run: `python3 walkthrough.py demo '+x.lesson+'`\n\n':''}Source: ${x.source}\n`).join('\n'));
pptx.writeFile({fileName:path.join(__dirname,'SCALE-LI_SOTA_Walkthrough.pptx')});
